name: Go CI on Pr

on:
  workflow_call: {}

jobs:
  fmt:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Check Go formatting
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/fmt }

  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Lint Go
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/lint }

  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Run Go tests
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/test }

  vuln:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Check Go vulnerabilities
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/vuln }
