name: Nix CI on Pr

on:
  workflow_call:
    inputs:
      environment:
        description: Environment variables of every job as a JSON object.
        type: string
        default: '{}'

jobs:
  fmt:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env: ${{ fromJSON(inputs.environment) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check Nix formatting
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with:
          command: ci/nixos/fmt

  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env: ${{ fromJSON(inputs.environment) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Lint Nix
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with:
          command: ci/nixos/lint
