name: Nix CI on Pr

on:
  workflow_call: {}

jobs:
  fmt:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Check Nix formatting
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/fmt }

  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Lint Nix
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/lint }
