name: Static site CI

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Build static site
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/build }

  audit:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Audit dependencies
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/audit }

  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Run tests
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/test }
