name: Terraform CI

on:
  workflow_call: {}

jobs:
  fmt:
    name: Terraform format
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Check Terraform formatting
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/terraform-fmt }

  validate:
    name: Terraform validate
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Validate Terraform
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/terraform-validate }

  plan:
    name: Terraform plan
    needs: [fmt, validate]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Run Terraform plan
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with:
          command: |
            ci/terraform-plan 2>&1 | {
              printf '## Terraform plan\n\n~~~text\n'
              cat
              printf '\n~~~\n'
            } | tee -a "$GITHUB_STEP_SUMMARY"
