name: Terraform CI

on:
  workflow_call: {}

jobs:
  terraform-fmt:
    name: Terraform format
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Check Terraform formatting
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/terraform-fmt }

  terraform-validate:
    name: Terraform validate
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Validate Terraform
        uses: mr-chelyshkin/actions/invoke-taskfile@v1
        with: { command: ci/terraform-validate }

  check-job-results:
    if: always()
    needs: [terraform-fmt, terraform-validate]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check job results
        uses: mr-chelyshkin/actions/check-job-results@v1
        with:
          results: ${{ toJSON(needs) }}
